springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  jpa:
    properties:
      hibernate:
        default_schema: time_tracker
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    open-in-view: false
    show-sql: false

app:
  time:
    zone: ${TIME_ZONE:Europe/Moscow}
    time-to-close: ${TIME_TO_CLOSE:0 0 17 * * *}

  security:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: ${JWT_EXPIRATION}
