springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: time_tracker
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    open-in-view: false

app:
  security:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: ${JWT_EXPIRATION}